@userId=1

### CREATE
POST http://localhost:${1:3000}/${2:users}
Content-Type: application/json

{
  "name": "User123",
  "email": "user123@test.com"
}

### READ ALL
GET http://localhost:${1:3000}/${2:users}

### READ ONE
GET http://localhost:${1:3000}/${2:users}/{{userId}}

### UPDATE
PUT http://localhost:${1:3000}/${2:users}/{{userId}}
Content-Type: application/json

{
  "name": "User123 update",
  "email": "user123update@test.com"
}

### DELETE
DELETE http://localhost:${1:3000}/${2:users}/{{userId}}
