# @ADMIN_TOKEN={{\$dotenv ADMIN_TOKEN}}
@TOKEN={{\$processEnv TOKEN}}

### GET users
# @name getUsers
@headerContenType={{getUsers.response.headers.Content-Type}}
@bodyLength={{getUsers.response.body.length}}

GET https://jsonplaceholder.typicode.com/users

### POST users
POST https://jsonplaceholder.typicode.com/users
Content-Type: application/json

{
    // .env Variables
    "dotenv_TOKEN": "{{\$dotenv TOKEN}}",
    // System Variables
    "processEnv_TOKEN": "{{\$processEnv TOKEN}}",
    "TOKEN": "{{TOKEN}}",
    "USERNAME": "{{\$processEnv USERNAME}}",
    "OS": "{{\$processEnv OS}}",
    // Request Variables
    "headerContenType": "{{headerContenType}}",
    "bodyLength": "{{bodyLength}}",
    // Global Variables
    "guid": "{{\$guid}}",
    "timestamp": "{{\$timestamp}}",
    "timestamp-s": "{{\$timestamp -1740224464 s}}",
    "timestamp-5h": "{{\$timestamp -5 h}}",
    "randomInt": "{{\$randomInt 1 999}}",
    "datetime": "{{\$datetime iso8601}}",
    "datetime-YYYY-MM-DD": "{{\$datetime 'YYYY-MM-DD'}}",
    "localDatetime": "{{\$localDatetime 'YYYY-MM-DD-HH:mm:ss'}}"
}

###

### Prompt Variables
# @prompt promptVar
POST https://jsonplaceholder.typicode.com/users
Content-Type: application/json

{
    //Prompt Variables
    "promptVar": "{{promptVar}}"
}