### Get all ${1:user}
GET http://localhost:${2:3000}/api/${1}/findAll
Content-Type: application/json

### Get a ${1} by ID
GET http://localhost:${2}/api/${1}/findOne/1
Content-Type: application/json

### Create a new ${1}
POST http://localhost:${2}/api/${1}/create
Content-Type: application/json

{
  "name": "Juan",
  "email": "juan@example.com"
}

### Update a ${1}
PUT http://localhost:${2}/api/${1}/update/1
Content-Type: application/json

{
  "name": "Juan Updated"
}

### Delete a ${1}
DELETE http://localhost:${2}/api/${1}/remove/1
Content-Type: application/json
