@token={{\$dotenv TOKEN}}

### GET
GET http://localhost:3000

### POST
POST https://jsonplaceholder.typicode.com/users
Content-Type: application/json

{
    // .env Variables
    "dotenv_TOKEN": "{{\$dotenv TOKEN}}",
    // System Variables
    "processEnv_TOKEN": "{{\$processEnv TOKEN}}"
}

### GET
GET https://jsonplaceholder.typicode.com/users